# Generated by Django 5.0.1 on 2024-01-14 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='garage',
            name='log',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.garage'),
        ),
    ]
